name:                ChordP2P
version:             0.1.0.0
github:              "abodhare/ChordP2P"
license:             BSD3
author:              "abodhare"
maintainer:          "example@example.com"
copyright:           "2020 abodhare"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ChordP2P#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- hashtables
- hashable
- network
- network-simple

library:
  source-dirs: src

executables:
  ChordP2P-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ChordP2P

tests:
  ChordP2P-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ChordP2P
